[18.0][MIG] product_template_tags_code: Migration to 18.0
Kimkhoi3010/product-attribute pull request #6
Opened 2024-12-04 05:08 UTC by Kimkhoi3010

2024-12-04 09:01 UTC, natuan9 approved these changes

2024-12-09 10:07 UTC, xaviedoanhduy requested changes
please amend commit `[IMP] product_template_tags_code: Change module name product_tags_code` to `[MOV] product_template_tags_code: product_template_tags_code becomes product_tags_code`

2024-12-09 10:14 UTC, xaviedoanhduy commented
also add PR description for the PR on OCA side

2024-12-12 08:54 UTC, xaviedoanhduy approved these changes

2025-06-24 04:19 UTC, merged